version: '3.4'

services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  overload.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SubscriptionClientName=Payment
      - RabbitMqConfig__EventBusConnection=rabbitmq
      - RabbitMqConfig__EventBusUserName=guest
      - RabbitMqConfig__EventBusPassword=guest
      - RabbitMqConfig__EventBusRetryCount=5
    ports:
      - "7000:80"

  overload.logging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SubscriptionClientName=Logging
      - RabbitMqConfig__EventBusConnection=rabbitmq
      - RabbitMqConfig__EventBusUserName=guest
      - RabbitMqConfig__EventBusPassword=guest
      - RabbitMqConfig__EventBusRetryCount=5
    ports:
      - "7001:80"

  overload.ids.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SubscriptionClientName=UserIntergration
      - RabbitMqConfig__EventBusConnection=rabbitmq
      - RabbitMqConfig__EventBusUserName=guest
      - RabbitMqConfig__EventBusPassword=guest
      - RabbitMqConfig__EventBusRetryCount=5
    ports:
      - "7003:80"

  overload.gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002:80"

  overload.reporting.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9009:80"

networks:
  default:
    external:
      name: overload_network
