version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    volumes:
      - overload-rabbitmq:/var/lib/rabbitmq
    networks:
      - overload_network

  overload.payment.api:
    image: ${DOCKER_REGISTRY-}overloadpaymentapi
    build:
      context: .
      dockerfile: src/Services/Payment/Overload.Payment.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - overload_network

  overload.logging.api:
    image: ${DOCKER_REGISTRY-}overloadloggingapi
    build:
      context: .
      dockerfile: src/Services/Logging/Overload.Logging.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - overload_network

  overload.ids.api:
    image: ${DOCKER_REGISTRY-}overloadids
    build:
      context: .
      dockerfile: src/Services/Ids/Overload.Ids/Dockerfile
    networks:
      - overload_network

  overload.gateway.api:
    image: ${DOCKER_REGISTRY-}overloadgateway
    build:
      context: .
      dockerfile: src/Services/Gateways/Overload.Gateways.Api/Dockerfile
    networks:
      - overload_network

  overload.reporting.api:
    image: ${DOCKER_REGISTRY-}overloadreporting
    build:
      context: .
      dockerfile: src/Services/Reporting/Overload.Reporting.Service/Dockerfile
    networks:
      - overload_network

volumes:
  overload-rabbitmq:

networks:
  overload_network:




